name: Setup Steps
runs:
  using: composite
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Make Gradle executable (if needed)
      shell: bash
      run: chmod +x ./gradlew

    - name: Gradle cache
      uses: gradle/actions/setup-gradle@v3