name: Android Connected Tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: {}
jobs:
  connected:
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: ./gradlew assembleDebug assembleAndroidTest --stacktrace
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_6
          force-avd-creation: true
          emulator-options: -no-snapshot -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest --stacktrace
      - name: Upload connected test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: connected-test-report
          path: |
            **/build/reports/androidTests/connected/**
            **/build/outputs/androidTest-results/connected/**