name: Android Unit Tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: {}
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - uses: ./.github/actions/setup

      - name: Unit Test
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Upload unit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: |
            **/build/reports/tests/testDebugUnitTest/**
            **/build/test-results/testDebugUnitTest/**