name: Android Connected Tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: {}
jobs:
  connected:
    runs-on: macos-14
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

        # AVD/ADB 캐시 (초기 부팅/설치 시간 크게 단축)
#      - name: Cache Android AVD
#        id: avd-cache
#        uses: actions/cache@v4
#        with:
#          path: |
#            ~/.android/avd
#            ~/.android/adb
#          key: avd-${{ runner.os }}-api33-arm64-googleapis-v1


        # 혹시 남아 있을 수 있는 ADB/에뮬레이터 프로세스 정리
      - name: Pre-clean emulator/adb
        shell: bash
        run: |
          pkill -f "qemu-system" || true
          pkill -f "emulator" || true
          adb kill-server || true

      - name: Emulator version
        run: $ANDROID_HOME/emulator/emulator -version || true

      # 에뮬레이터 실행 + 테스트 (부팅대기는 액션이 책임)
      - name: Launch emulator & run connected tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: aosp_atd
          arch: arm64-v8a
          profile: pixel_6
          force-avd-creation: true
          emulator-options: >-
            -no-snapshot -no-window -gpu swiftshader_indirect
            -noaudio -no-boot-anim -wipe-data
            -camera-back none -camera-front none
            -accel on
          disable-animations: true
          # 기본 부팅대기(10분)로 충분. 필요시 600000 정도까지.
          emulator-boot-timeout: 600000
          emulator-channel: stable
          script: |
            ./gradlew --stacktrace connectedDebugAndroidTest
      

      - name: Upload connected test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: connected-test-report
          path: |
            **/build/reports/androidTests/connected/**
            **/build/outputs/androidTest-results/connected/**