name: Android Connected Tests
on:
  workflow_dispatch: {}
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, ready_for_review, labeled]
    paths-ignore: [ '**.md', 'docs/**' ]
  push:
    branches: [ master ]   # merge된 커밋에서 실행
    paths-ignore: [ '**.md', 'docs/**' ]
  schedule:
    - cron: '0 18 * * *'   # 매일 03:00 KST (UTC 18:00)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  connected:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Cache AVD
        uses: actions/cache@v4
        with:
          path: |
            ~/.android/avd
            ~/.android/adb
          key: avd-api33-x86_64
          restore-keys: |
            avd-

      - name: Emulator version
        run: $ANDROID_HOME/emulator/emulator -version || true

      - name: Launch emulator & run connected tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: default
          arch: x86_64
          profile: pixel_2
          force-avd-creation: false
          emulator-options: >-
            -no-window -gpu swiftshader_indirect -no-boot-anim
            -noaudio -no-boot-anim -camera-back none -camera-front none
            -accel on
          emulator-boot-timeout: 600000
          channel: stable
          script: |
            adb wait-for-device
            adb shell 'while [[ -z "$(getprop sys.boot_completed)" ]]; do sleep 1; done; input keyevent 82'
            ./gradlew --stacktrace connectedDebugAndroidTest

      - name: Upload connected test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: connected-test-report
          path: |
            **/build/reports/androidTests/connected/**
            **/build/outputs/androidTest-results/connected/**