name: Android CI

on:
  push:
    branches-ignore: ["spike/**"]
    paths-ignore: [ '**.md', 'docs/**' ]   # ← .github/** 는 제외하지 않는 걸 권장
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup (JDK/Gradle cache)
        uses: ./.github/actions/setup

      # 스모크 + 정적체크 (빠르게 실패하도록)
      - name: Assemble & static checks
        run: |
          ./gradlew \
            assembleDebug \
            lintDebug \
            --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7