name: Emulator Boot Smoke
on: workflow_dispatch
jobs:
  boot:
    runs-on: macos-13
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }

      - run: $ANDROID_HOME/emulator/emulator -version || true

      - name: Start emulator (Intel x86_64)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          avd-name: ci-api33-x86
          cores: 2
          ram-size: 2048
          heap-size: 384M
          force-avd-creation: true
          emulator-options: >-
            -no-window -gpu swiftshader_indirect -no-boot-anim
            -no-snapshot -no-snapshot-load -no-snapshot-save -wipe-data
            -accel on
          emulator-boot-timeout: 600000
          channel: stable
          script: |
            adb wait-for-device
            adb shell 'while [[ -z "$(getprop sys.boot_completed)" ]]; do sleep 1; done; input keyevent 82'