name: Emulator Boot Smoke
on: workflow_dispatch
jobs:
  boot:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }

      - run: $ANDROID_HOME/emulator/emulator -version || true

      - name: Start emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: default
          arch: x86_64
          profile: pixel_6
          force-avd-creation: true
          emulator-options: >-
            -no-window -gpu swiftshader_indirect -no-boot-anim
            -no-snapshot -noaudio -no-boot-anim -camera-back none -camera-front none
            -accel on
          emulator-boot-timeout: 600000
          channel: stable
          script: |
            adb wait-for-device
            adb shell 'while [[ -z "$(getprop sys.boot_completed)" ]]; do sleep 1; done; input keyevent 82'