name: Emulator Boot Smoke
on: workflow_dispatch
jobs:
  boot:
    runs-on: macos-14
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }
      - name: Emulator version
        run: $ANDROID_HOME/emulator/emulator -version || true
      - name: Start emulator only (no gradle)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: arm64-v8a
          force-avd-creation: true
          emulator-options: >-
            -verbose -no-snapshot -no-window -gpu swiftshader_indirect
            -noaudio -no-boot-anim -wipe-data
            -camera-back none -camera-front none
            -accel on
          emulator-boot-timeout: 600000
          script: |
            adb devices -l
            adb shell getprop ro.build.description
            adb shell getprop sys.boot_completed